version: '3.3'

services:

    node:
        build:
            context: ./node
            args:
                - NODE_VERSION=latest
                - PROJECT_PATH=/opt/app/
                - NODE_ENV=development
                - YARN=false
        volumes:
            - ./:/opt/app
        entrypoint: run-nodock "node ./bin/www"
        tty: true
        ports:
            - "3000:3000"
    mysql:
        image: mysql:5.7
        restart: on-failure
        environment:
            MYSQL_DATABASE: ${ENV_DB_NAME}
#            MYSQL_USER: ${ENV_DB_USER}
#            MYSQL_PASSWORD: ${ENV_DB_PASS}
            MYSQL_ROOT_PASSWORD: ${ENV_DB_PASS}
        ports:
            - "3306:3306"
        links:
            - node
    nginx:
        build:
            context: ./nginx
            args:
                - WEB_REVERSE_PROXY_PORT=8000
                - WEB_SSL=false
                - SELF_SIGNED=false
                - NO_DEFAULT=false
        volumes:
            - ./data/logs/nginx/:/var/log/nginx
        ports:
            - "80:80"
            - "443:443"
        tty: true
volumes:
    mysql-data: